name: Build Linux GNU

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran cmake openmpi-bin libopenmpi-dev

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests (CTest)
        run: |
          cd build
          ctest --output-on-failure
