name: Build Linux Intel Classic

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: "Install Intel compilers & MPI"
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        with:
          install-classic: true
          install-mpi: true
          install-openmp: true
          mpi-wrapper-setup: classic

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure CMake
        shell: bash
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -S . -B build \
            -DCMAKE_C_COMPILER=icc \
            -DCMAKE_CXX_COMPILER=icpc \
            -DCMAKE_Fortran_COMPILER=ifort

      - name: Build
        shell: bash
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake --build build --parallel

      - name: Run tests (CTest)
        shell: bash
        env:
          I_MPI_ALLOW_RUN_AS_ROOT: "1"
          I_MPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
        run: |
          source /opt/intel/oneapi/setvars.sh
          cd build
          ctest --output-on-failure
