name: Build Linux Intel LLVM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: "Install Intel compilers & MPI"
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        with:
          install-oneapi: true
          install-mpi: true
          install-openmp: true
          mpi-wrapper-setup: oneapi

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure CMake
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake -S . -B build \
            -DCMAKE_C_COMPILER=icx \
            -DCMAKE_CXX_COMPILER=icpx \
            -DCMAKE_Fortran_COMPILER=ifx

      - name: Build
        run: |
          source /opt/intel/oneapi/setvars.sh
          cmake --build build --parallel

      - name: Run tests (CTest)
        run: |
          source /opt/intel/oneapi/setvars.sh
          cd build
          ctest --output-on-failure
